apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config:
    address-pools:
    - name: sinlge-ip
      protocol: layer2
      addresses:
      - 192.168.49.69-192.168.49.69