apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  labes:
    app: nginx
spec:
  selector:
    matchLables:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      spec:
        containers:
        - image: gaspacho_nginx
          imagePullPolicy: Never
          name: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: key
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer