apiVersion: apps/v1
kind: Deployment
metadata: 
  labes: 
    app: nginx
  name: nginx
spec: 
  replicas: 1
  selector: 
    matchLables: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
      spec: 
        containers: 
          - 
            image: gaspacho_nginx
            imagePullPolicy: Never
            name: nginx
--- 
apiVersion: v1
kind: Service
metadata: 
  annotations: 
    metallb.universe.tf/allow-shared-ip: key
  name: nginx
spec: 
  ports: 
    - 
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: nginx
  type: LoadBalancer
