apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: wordpress
  name: wordpress
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: wordpress
  template: 
    metadata: 
      labels: 
        app: wordpress
    spec: 
      containers: 
        - 
          image: gaspacho_nginx
          imagePullPolicy: Never
          name: wordpress
          ports: 
            - 
              containerPort: 5050

---

apiVersion: v1
kind: Service
metadata: 
  annotations: 
    metallb.universe.tf/allow-shared-ip: key
  name: wordpress
spec: 
  ports: 
    - 
      name: wordpress
      port: 5050
      protocol: TCP
      targetPort: 5050
  selector: 
    app: wordpress
  type: LoadBalancer
